build(auto): 👷 enable auto-merge for omnibotent PRs

diff --git a/.github/workflows/auto-pr-cargo-fixes.yaml b/.github/workflows/auto-pr-cargo-fixes.yaml
--- a/.github/workflows/auto-pr-cargo-fixes.yaml
+++ b/.github/workflows/auto-pr-cargo-fixes.yaml
@@ -32,6 +32,8 @@ env:
   RUSTC_BOOTSTRAP: 1
   # Which branch to use to make the pull request
   PR_BRANCH: auto/cargo_fix
+  # Whether or not to enable auto-merge
+  PR_AUTO_MERGE: false
 
 
 jobs:
@@ -210,6 +212,23 @@ jobs:
               --repo "${{ github.repository }}" \
               --add-label rust
           fi
+
+      - name: Enable auto-merge
+        if: ${{ env.PR_AUTO_MERGE == 'true' }}
+        env:
+          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
+        run: |
+          NUM=$(gh pr view "${{ env.PR_BRANCH }}" \
+                  --repo "${{ github.repository }}" \
+                  --json number --jq '.number' || \
+                echo "")
+
+          if [[ -z "$NUM" ]]; then
+            echo "Failed to get PR number"
+            exit 1
+          fi
+
+          gh pr merge --squash --auto --body "" "$NUM"
 
 
   close-pr:
diff --git a/.github/workflows/auto-pr-yarn-dependencies.yaml b/.github/workflows/auto-pr-yarn-dependencies.yaml
--- a/.github/workflows/auto-pr-yarn-dependencies.yaml
+++ b/.github/workflows/auto-pr-yarn-dependencies.yaml
@@ -30,6 +30,8 @@ defaults:
 env:
   # Which branch to use to make the pull request
   PR_BRANCH: auto/yarn_update
+  # Whether or not to enable auto-merge
+  PR_AUTO_MERGE: true
 
 
 jobs:
@@ -305,6 +307,23 @@ jobs:
               --add-label dependencies \
               --add-label javascript
           fi
+
+      - name: Enable auto-merge
+        if: ${{ env.PR_AUTO_MERGE == 'true' }}
+        env:
+          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
+        run: |
+          NUM=$(gh pr view "${{ env.PR_BRANCH }}" \
+                  --repo "${{ github.repository }}" \
+                  --json number --jq '.number' || \
+                echo "")
+
+          if [[ -z "$NUM" ]]; then
+            echo "Failed to get PR number"
+            exit 1
+          fi
+
+          gh pr merge --squash --auto --body "" "$NUM"
 
 
   close-pr:
